# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suga < Formula
  desc "Suga CLI"
  homepage "https://app.addsuga.com/"
  version "0.1.16"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.16/suga_0.1.16_darwin_amd64.tar.gz"
      sha256 "e58b52ee5aedf179b0da1da16809801b0fe8ddc07be92472f04282afa57033df"

      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.16/suga_0.1.16_darwin_arm64.tar.gz"
      sha256 "f29f5e3ab4d54d3f83dabde7c95c577eb78c236506568c917290e5a78108d2c7"

      def install
        bin.install "suga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.16/suga_0.1.16_linux_amd64.tar.gz"
      sha256 "72629646f5b151bfb78583df20c76cb034799875533f8b69711621d36a18926f"
      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.16/suga_0.1.16_linux_arm64.tar.gz"
      sha256 "8bdc449a33fe579a5b6d12471b67069a694b3adafe9bd210eb7be5cc4ac9366a"
      def install
        bin.install "suga"
      end
    end
  end
end
