# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suga < Formula
  desc "Suga CLI"
  homepage "https://app.addsuga.com/"
  version "0.1.9"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.9/suga_0.1.9_darwin_amd64.tar.gz"
      sha256 "70553bfe3c761649f0c78e4050dc95eed1582b1840741ee8d38484e3acc1d0bf"

      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.9/suga_0.1.9_darwin_arm64.tar.gz"
      sha256 "d4e52938b0a4434238a9027cc2b75f955ddb05e78e8f9c19df631788f54b3533"

      def install
        bin.install "suga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.9/suga_0.1.9_linux_amd64.tar.gz"
      sha256 "dd6f888f8441f708deea6b8512ce7d8ac2617473f667126abd83e025882f7e42"
      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.1.9/suga_0.1.9_linux_arm64.tar.gz"
      sha256 "6c1bf0cb89b6436a24707523faf8aaad8107987f29520518fd995ef04565e2c6"
      def install
        bin.install "suga"
      end
    end
  end
end
