# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suga < Formula
  desc "Suga CLI"
  homepage "https://app.addsuga.com/"
  version "0.6.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nitrictech/suga/releases/download/v0.6.0/suga_0.6.0_darwin_amd64.tar.gz"
      sha256 "6689ed672e2398191132a4510f2e45bec0480fd8eb8e7c2e6dba0889dd323c2a"

      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nitrictech/suga/releases/download/v0.6.0/suga_0.6.0_darwin_arm64.tar.gz"
      sha256 "0f59fa1cb6b444966055755fe04f243969ce400b2b31f64e1e774df7f55749f4"

      def install
        bin.install "suga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.6.0/suga_0.6.0_linux_amd64.tar.gz"
      sha256 "b4d8a044b873b72cc00f8f3c55ee4b641e2eaa489b60eef45c4d37abaf8b1f99"
      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.6.0/suga_0.6.0_linux_arm64.tar.gz"
      sha256 "3c516f1acd5dc593c584e00e81cadac4427e8f59780835380fde8e2dfdae3223"
      def install
        bin.install "suga"
      end
    end
  end
end
